# Generated by Django 6.0.6 on 2026-06-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='profile',
            name='dog_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='愛犬の誕生日'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dog_gender',
            field=models.CharField(blank=True, choices=[('male', '男の子'), ('female', '女の子'), ('unknown', '内緒 / 不明')], default='unknown', max_length=10, verbose_name='ワンちゃんの性別'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dog_image',
            field=models.ImageField(blank=True, null=True, upload_to='dog_profiles/', verbose_name='ワンちゃんの写真'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dog_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='愛犬の名前'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='飼い主のニックネーム'),
        ),
    ]
