# Generated by Django 6.0.6 on 2026-06-19 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_profile_address1_remove_profile_address2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='お散歩日')),
                ('time_of_day', models.CharField(choices=[('morning', '朝'), ('noon', '昼'), ('evening', '夕方'), ('night', '夜')], default='morning', max_length=10, verbose_name='時間帯')),
                ('note', models.TextField(blank=True, null=True, verbose_name='お散歩メモ')),
                ('walk_image', models.ImageField(blank=True, null=True, upload_to='walk_logs/', verbose_name='お散歩写真')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='飼い主')),
            ],
        ),
    ]
