# Generated by Django 6.0.6 on 2026-06-26 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_walklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='walklog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_logs', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
    ]
