# Generated by Django 6.0.6 on 2026-06-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_walklog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='base.profile', verbose_name='フォロー中'),
        ),
    ]
