# Generated by Django 6.0.6 on 2026-06-29 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='書き込み日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='コメントした人')),
                ('walk_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.walklog', verbose_name='対象のお散歩ログ')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
