# Generated by Django 6.0.6 on 2026-06-29 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'コメント'), ('like', 'いいね')], max_length=10)),
                ('is_read', models.BooleanField(default=False, verbose_name='既読フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通知日時')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.comment', verbose_name='対象のコメント')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='アクションしたユーザー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='通知を受け取るユーザー')),
                ('walk_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.walklog', verbose_name='対象のお散歩ログ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
