# Generated by Django 6.0.6 on 2026-06-30 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_posts/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_posts', to=settings.AUTH_USER_MODEL, verbose_name='お店ユーザー')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
