# Generated by Django 6.0.6 on 2026-06-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_shoppost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shop',
            field=models.BooleanField(default=False, verbose_name='お店ユーザー'),
        ),
    ]
