# Generated by Django 6.0.6 on 2026-06-30 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_is_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お店の名前')),
                ('description', models.TextField(blank=True, null=True, verbose_name='お店の紹介文')),
                ('hours', models.CharField(max_length=100, verbose_name='営業時間')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='ホームページURL')),
                ('location', models.CharField(max_length=255, verbose_name='場所・住所')),
                ('map_iframe', models.TextField(blank=True, help_text='Googleマップの『地図を埋め込む』から取得した<iframe>タグをそのまま貼り付けてください。', null=True, verbose_name='Googleマップ埋め込みコード')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
