# Generated by Django 6.0.6 on 2026-07-01 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_shopprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='shop_image',
            field=models.ImageField(blank=True, default='shop_images/default_shop.png', null=True, upload_to='shop_images/', verbose_name='店舗画像'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='shop_name',
            field=models.CharField(default='', max_length=100, verbose_name='店舗名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
