# Generated by Django 6.0.6 on 2026-07-01 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_shopprofile_name_shopprofile_shop_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='書き込み日時')),
                ('shop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to='base.shoppost', verbose_name='対象のお知らせ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='コメントしたユーザー')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='base.shoppost', verbose_name='対象のお知らせ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー')),
            ],
            options={
                'unique_together': {('shop_post', 'user')},
            },
        ),
    ]
