# Generated by Django 6.0.6 on 2026-07-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_shoppostcomment_shoppostlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='allows_large_dogs',
            field=models.BooleanField(default=False, verbose_name='大型犬OK'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='has_dog_run',
            field=models.BooleanField(default=False, verbose_name='ドッグランあり'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='駐車場あり'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='店内ペット同伴OK'),
        ),
    ]
