# Generated by Django 6.0.6 on 2026-07-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_shopprofile_allows_large_dogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='hours',
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='閉店時間'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='is_closed_fri',
            field=models.BooleanField(default=False, verbose_name='定休日：金曜日'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='is_closed_mon',
            field=models.BooleanField(default=False, verbose_name='定休日：月曜日'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='is_closed_sat',
            field=models.BooleanField(default=False, verbose_name='定休日：土曜日'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='is_closed_sun',
            field=models.BooleanField(default=False, verbose_name='定休日：日曜日'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='is_closed_thu',
            field=models.BooleanField(default=False, verbose_name='定休日：木曜日'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='is_closed_tue',
            field=models.BooleanField(default=False, verbose_name='定休日：火曜日'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='is_closed_wed',
            field=models.BooleanField(default=False, verbose_name='定休日：水曜日'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開店時間'),
        ),
    ]
