# Generated by Django 6.0.6 on 2026-07-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_shopprofile_hours_shopprofile_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppost',
            name='category',
            field=models.CharField(choices=[('news', 'お知らせ'), ('coupon', 'クーポン'), ('event', 'イベント')], default='news', max_length=10, verbose_name='カテゴリ'),
        ),
    ]
